apiVersion: apps/v1
kind: Deployment
metadata:
   name: mainapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainapp
  template:
    metadata:
      labels:
        app: mainapp
    spec:
      containers:
      - name: mainapp
        image: shehan97105/mainapp:latest
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: mainapp
  labels:
    app: mainapp
spec:
  selector:
    type: NodePort
    app: mainapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000