apiVersion: apps/v1
kind: Deployment
metadata:
   name: mainapp-prod
   namespace: prod-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainapp-prod
  strategry:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: mainapp-prod
    spec:
      containers:
      - name: mainapp-prod
        image: shehan97105/mainapp:v2
        ports:
        - containerPort: 5000
