apiVersion: apps/v1
kind: Deployment
metadata:
   name: mainapp-dev
   namespace: dev-env
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainapp-dev
  template:
    metadata:
      labels:
        app: mainapp-dev
    spec:
      containers:
      - name: mainapp-dev
        image: shehan97105/mainapp:v2
        ports:
        - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: main
  namespace: dev-env
  labels:
    app: main
spec:
  selector:
    app: main
  ports:
    - name: http
      port: 80
      targetPort: 5000
  type: LoadBalancer